AWSTemplateFormatVersion: "2010-09-09"
Resources:
  TfstateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: isucon11-final-practice-infra-tfstate
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
