version: "3"

vars:
  AWS_PROFILE: wakye5815

  TERRAFORM_VERSION: 1.6

tasks:
  aws-cli:
    internal: true
    cmds:
      - docker run --rm -ti -v ~/.aws:/root/.aws -v $(pwd):/aws amazon/aws-cli {{.COMMAND}} --profile {{.AWS_PROFILE}}

  init-tf-aws-backend:
    cmds:
      - task: aws-cli
        vars:
          COMMAND: cloudformation deploy --template-file init_tf_aws_backend_cfn.yml --stack-name InitTfBackend --region ap-northeast-1

  aws-tf:
    dir: ./terraform/aws
    cmds:
      - docker run --rm -ti -v ~/.aws:/root/.aws -v $(pwd):/aws -w /aws/entrypoint -e AWS_PROFILE={{.AWS_PROFILE}} hashicorp/terraform:{{.TERRAFORM_VERSION}} {{.CLI_ARGS}}
